# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: pay/v0/service.proto
# plugin: python-betterproto
import logging


import allure
from dataclasses import dataclass

import betterproto


@dataclass
class OnCallbackReq(betterproto.Message):
    # 回调消息，json
    msg_content: str = betterproto.string_field(1)


@dataclass
class OnCallbackResp(betterproto.Message):
    """这是自定义类型，返回纯文本"""

    # text/plain
    content_type: str = betterproto.string_field(1)
    # 文本内容
    data: bytes = betterproto.bytes_field(2)


class PayStub(betterproto.ServiceStub):
    """内部支付服务"""

    @allure.step("""支付通知接口""")
    def on_callback(self, request: OnCallbackReq) -> OnCallbackResp:
        """支付通知接口"""
        logging.getLogger(__name__).info(
            "start call " + "[on_callback]" + " api" + "=>" + """支付通知接口"""
        )
        response = OnCallbackResp()
        self._do_twirp_rpc("/pay.v0.Pay/OnCallback", request, response)
        logging.getLogger(__name__).info("call " + "[on_callback]" + " api success!")
        return response
