
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-18T19:29:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "65ffd2b1c0abb0bdecc1a156731cf6ad643f2d85",
 "version": "2020.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
