
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-15T14:17:54+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "80927bd5875ab5cb8f7acdf379b945a5b2a0a16e",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
