
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9b48a27fa178d4ef7b1eb92e9b88038fa640bc57",
 "version": "0.24.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
