# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aiopdhttp
from aiopdhttp.models.run_linear_positions_request import RunLinearPositionsRequest  # noqa: E501
from aiopdhttp.rest import ApiException


class TestRunLinearPositionsRequest(unittest.TestCase):
    """RunLinearPositionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunLinearPositionsRequest(self):
        """Test RunLinearPositionsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aiopdhttp.models.run_linear_positions_request.RunLinearPositionsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
