
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-20T00:02:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecab137b56dc5aaa16cc14d39518f3f3e392a137",
 "version": "0.8.153"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
