#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['teek', 'teek._widgets', 'teek.extras']

package_data = \
{'': ['*']}

extras_require = \
{'image_loader': ['pillow', 'reportlab', 'svglib==0.9.0', 'lxml'],
 'soup_viewer': ['beautifulsoup4', 'lxml']}

setup(name='teek',
      version='0.6',
      description='Teek is a pythonic alternative to tkinter.',
      author='Akuli',
      author_email='akuviljanen17@gmail.com',
      url='https://github.com/Akuli/teek',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.5',
     )
