
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-16T14:49:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ad4b39c21db2cb5cf525320ef09953e7815d75f",
 "version": "2.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
