
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-20T11:19:24+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac2031da51ea5da9a7f58b1001fca3c4b2f1e921",
 "version": "1.2.4-alpha.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
