
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "authors": [
  "Padraic Shafer"
 ],
 "date": "2019-02-04T17:08:24-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "eebee5c564c9910e7ad4e4106d24330313e692e7",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
