# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import morpho_pb2 as morpho__pb2


class MorphoServiceStub(object):
    """The DTA service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransformDocument = channel.unary_unary(
                '/morpho.MorphoService/TransformDocument',
                request_serializer=morpho__pb2.TransformDocumentRequest.SerializeToString,
                response_deserializer=morpho__pb2.TransformDocumentResponse.FromString,
                )
        self.ListServices = channel.unary_unary(
                '/morpho.MorphoService/ListServices',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=morpho__pb2.ListServicesResponse.FromString,
                )
        self.TransformDocumentPipe = channel.unary_unary(
                '/morpho.MorphoService/TransformDocumentPipe',
                request_serializer=morpho__pb2.TransformDocumentPipeRequest.SerializeToString,
                response_deserializer=morpho__pb2.TransformDocumentResponse.FromString,
                )


class MorphoServiceServicer(object):
    """The DTA service definition.
    """

    def TransformDocument(self, request, context):
        """Request to transform a plain text document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServices(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransformDocumentPipe(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MorphoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransformDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformDocument,
                    request_deserializer=morpho__pb2.TransformDocumentRequest.FromString,
                    response_serializer=morpho__pb2.TransformDocumentResponse.SerializeToString,
            ),
            'ListServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServices,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=morpho__pb2.ListServicesResponse.SerializeToString,
            ),
            'TransformDocumentPipe': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformDocumentPipe,
                    request_deserializer=morpho__pb2.TransformDocumentPipeRequest.FromString,
                    response_serializer=morpho__pb2.TransformDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'morpho.MorphoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MorphoService(object):
    """The DTA service definition.
    """

    @staticmethod
    def TransformDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morpho.MorphoService/TransformDocument',
            morpho__pb2.TransformDocumentRequest.SerializeToString,
            morpho__pb2.TransformDocumentResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morpho.MorphoService/ListServices',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            morpho__pb2.ListServicesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TransformDocumentPipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/morpho.MorphoService/TransformDocumentPipe',
            morpho__pb2.TransformDocumentPipeRequest.SerializeToString,
            morpho__pb2.TransformDocumentResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
