# Generated by Django 3.0.8 on 2020-07-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doubt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='resolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doubt')),
            ],
        ),
    ]
