
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-22T11:58:39+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "bddb165fbe14b2d87e1c980cbcc8aac58b4db6e7",
 "version": "0.0.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
