
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-21T22:56:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "73756f9987d883a4e282c1ad2c29cd1aca749016",
 "version": "v0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
