# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoNavigationNavigationProcedureSegment(Model):
    """Various pieces of information associated with a procedure segment.

    :param type: The segment type.
    :type type: str
    :param transition_id: The procedure segment id.
    :type transition_id: str
    :param sequence_number: The procedure segment sequence number.
    :type sequence_number: int
    :param track_code: The procedure segment
    :type track_code: str
    :param waypoint_id: The procedure segment waypoint id.
    :type waypoint_id: int
    :param waypoint_desc_codes: The procedure segment waypoint description
     codes.
    :type waypoint_desc_codes: list[str]
    :param waypoint_bearing: The bearing to the waypoint.
    :type waypoint_bearing: float
    :param waypoint_distance: The distance to the waypoint.
    :type waypoint_distance: float
    :param navaids: The navaids referenced by this segment.
    :type navaids:
     list[~emsapi.models.AdiEmsWebApiV2DtoNavigationNavigationProcedureSegmentNavaid]
    :param turn_direction: The procedure segment turn direction.
    :type turn_direction: str
    :param altitude_description: The procedure segment altitude description.
    :type altitude_description: str
    :param altitude1: The procedure segment altitude 1.
    :type altitude1: str
    :param altitude2: The procedure segment altitude 2.
    :type altitude2: str
    """

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'transition_id': {'key': 'transitionId', 'type': 'str'},
        'sequence_number': {'key': 'sequenceNumber', 'type': 'int'},
        'track_code': {'key': 'trackCode', 'type': 'str'},
        'waypoint_id': {'key': 'waypointId', 'type': 'int'},
        'waypoint_desc_codes': {'key': 'waypointDescCodes', 'type': '[str]'},
        'waypoint_bearing': {'key': 'waypointBearing', 'type': 'float'},
        'waypoint_distance': {'key': 'waypointDistance', 'type': 'float'},
        'navaids': {'key': 'navaids', 'type': '[AdiEmsWebApiV2DtoNavigationNavigationProcedureSegmentNavaid]'},
        'turn_direction': {'key': 'turnDirection', 'type': 'str'},
        'altitude_description': {'key': 'altitudeDescription', 'type': 'str'},
        'altitude1': {'key': 'altitude1', 'type': 'str'},
        'altitude2': {'key': 'altitude2', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(AdiEmsWebApiV2DtoNavigationNavigationProcedureSegment, self).__init__(**kwargs)
        self.type = kwargs.get('type', None)
        self.transition_id = kwargs.get('transition_id', None)
        self.sequence_number = kwargs.get('sequence_number', None)
        self.track_code = kwargs.get('track_code', None)
        self.waypoint_id = kwargs.get('waypoint_id', None)
        self.waypoint_desc_codes = kwargs.get('waypoint_desc_codes', None)
        self.waypoint_bearing = kwargs.get('waypoint_bearing', None)
        self.waypoint_distance = kwargs.get('waypoint_distance', None)
        self.navaids = kwargs.get('navaids', None)
        self.turn_direction = kwargs.get('turn_direction', None)
        self.altitude_description = kwargs.get('altitude_description', None)
        self.altitude1 = kwargs.get('altitude1', None)
        self.altitude2 = kwargs.get('altitude2', None)
