
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-16T06:26:23+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c319bfe624e04e0ee59c7a38a74c03bc1021128",
 "version": "0.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
