
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-14T17:27:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e00a318a4c04f147953bef2d7eb67af7933847cb",
 "version": "0.12.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
