
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-19T14:04:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e222cd2248dfa06a13882a869028159716adec7f",
 "version": "0.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
