
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "4ccfd8a1656e65d3f140216ebe9e7f822db87bf5",
 "version": "v1.3.0.7.0+15.g4ccfd8a1.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
