# Generated by Django 2.2.7 on 2020-07-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumnsspec',
            name='distinct_values',
            field=models.IntegerField(null=True),
        ),
    ]
