#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['linkcutter']

package_data = \
{'': ['*']}

setup(name='linkcutter',
      version='0.0.1a1',
      description='Make link shorter using cutt.ly API',
      author='Ilia Fedorovich',
      author_email='workplaceilfed@gmail.com',
      url=None,
      packages=packages,
      package_data=package_data,
     )
