
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "30951221c3c4d7197cae332c6f12499da5f1ab37",
 "version": "0.17.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
