
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-23T21:02:42+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ec493c745a40897c42d50cff6a66853addb2afa",
 "version": "v0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
