# coding: utf-8

"""
    Robot API

    Robot REST API  # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pdhttp
from pdhttp.models.run_joint_poses_request import RunJointPosesRequest  # noqa: E501
from pdhttp.rest import ApiException


class TestRunJointPosesRequest(unittest.TestCase):
    """RunJointPosesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunJointPosesRequest(self):
        """Test RunJointPosesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pdhttp.models.run_joint_poses_request.RunJointPosesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
