
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-21T03:05:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "41eb6c430ed49fb2fc78e1f9e6581eaf01f7b7cd",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
