
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "19ef30a88073225796b93e49aff0156e9446f9f3",
 "version": "2334"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
