# Generated by Django 3.0 on 2020-06-11 13:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_social_email_auth', '0003_emailconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which the paaword reset token was created.', verbose_name='created at')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The token that authorizes the user to reset their password.', verbose_name='key')),
                ('email', models.ForeignKey(editable=False, help_text='The email address used to request the password reset.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', related_query_name='password_reset_token', to='rest_social_email_auth.EmailAddress', verbose_name='email address')),
            ],
            options={
                'verbose_name': 'password reset token',
                'verbose_name_plural': 'password reset tokens',
            },
        ),
    ]
