
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-15T18:06:28+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "17f1012203db2e7ae03c4d429e3293b4911a441e",
 "version": "4.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
