
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-23T22:06:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b223e8d0ab16e8ea0b41c19e08d8c4d3f219ac20",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
