
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-17T22:53:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ff5bd42c4ea6f126bd498b70557b6f0d446d79e",
 "version": "0.1.0rc6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
