
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-18T12:32:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb65c644c6ca1963902233fbfa8e8ce963de663c",
 "version": "3.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
