# Generated by Django 3.0 on 2020-06-11 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_social_email_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='email')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('is_primary', models.BooleanField(default=False, help_text="Boolean indicating if the email is the user's primary address", verbose_name='is primary')),
                ('is_verified', models.BooleanField(default=False, help_text='Boolean indicating if the user has verified ownership ofthe email address', verbose_name='is verified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', related_query_name='email_address', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email address',
                'verbose_name_plural': 'email addresses',
            },
        ),
    ]
