
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-19T15:08:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "214a801e776be2fc24e65bc0023d913f56cebd45",
 "version": "0.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
