
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e7668d7a3c2818ef8ecdbd618ad34ca8b1369f99",
 "version": "2332"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
