# coding: utf-8

"""
    Dash Hudson - Insta

    A Smarter Way to Grow on Instagram  To use the following APIs you will need an access token. An access token can be obtained by contacting Dash Hudson support.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tomek@dashhudson.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import brandpanel
from brandpanel.models.user import User  # noqa: E501
from brandpanel.rest import ApiException


class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUser(self):
        """Test User"""
        # FIXME: construct object with mandatory attributes with example values
        # model = brandpanel.models.user.User()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
