
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-22T12:25:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3fdb769979db9cae3fe8e452c852d3fb5e2e1c08",
 "version": "1.11.1.post.dev144"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
