from tc2.envs.env import TC2Behavior
from tc2.envs.env import TC2Env
from tc2.envs.env import TC2Observation
from tc2.envs.demo import TC2EnvDemo
from tc2.envs.basic import TC2Env5Marine
from tc2.envs.basic import TC2Env5Zealot
from tc2.envs.basic import TC2Env5Mutalisk
from tc2.envs.basic import TC2Env3to7Marine
from tc2.envs.basic import TC2Env3to7Zealot
from tc2.envs.basic import TC2Env3to7Mutalisk
from tc2.envs.basic import TC2EnvVultureZealot
from tc2.envs.basic import TC2EnvWraith2Hydralisks
from tc2.envs.basic import TC2EnvMutalisk3Scourge
from tc2.envs.basic import TC2EnvMarineZealot
from tc2.envs.basic import TC2EnvFullGame
from tc2.envs.basic import TC2EnvGather
from tc2.envs.basic import TC2EnvTrainWorkers
from tc2.envs.basic import TC2EnvTrainMarines
from tc2.envs.benchmark import TC2EnvMoveToBeacon
