
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-22T17:10:01+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "36e2130f795ab6775b57347436f50bb408e4900e",
 "version": "4.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
