
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-24T17:20:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "104e1da51297a6e9f6e2d127e9df87dc3d6108de",
 "version": "0.4.119"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
