
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-22T18:01:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5991ff5e6836a971db24af9e5f6c7b19945cd754",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
