
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-23T18:49:15+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "91cd5dba4d848a02edbe73faa1b1032a1b10c1be",
 "version": "1.2.4-alpha.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
