# Generated by Django 3.0.3 on 2020-02-16 05:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0182_auto_20200215_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='ready_2_launch_detail',
            name='item_full_name_obj',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
