
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-20T14:33:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d68ce76115a4f573dd5767ede91943c93c476963",
 "version": "1.7.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
