
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-15T22:37:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7fe27914e8e5c6a84008eb4a696ee26470e37e37",
 "version": "0.3.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
