
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-25T07:04:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "09f1efff2e66d87a7e32c9ceca36e8df31cce0f4",
 "version": "v1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
