
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3338132dd830e5786c784cd67a75e4c4a3dd54c4",
 "version": "1.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
