
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-23T09:48:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "30ccbc68d26ae29b87e1e4c11ed89216949c719d",
 "version": "0.4.2.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
