#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pypungi']

package_data = \
{'': ['*']}

setup(name='pypungi',
      version='0.10.10',
      description='Helper tool',
      author='James Otterson',
      author_email='jjotterson@gmail.com',
      url='https://github.com/jjotterson',
      packages=packages,
      package_data=package_data,
     )
