
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "branch": "1.3.0)",
 "date": "2020-07-22T13:36:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a13ff677830c6a69592ba6dd1003cc26a6bea530",
 "repository": "https://github.com/metawards/MetaWards",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
