# Generated by Django 2.2 on 2020-07-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocontact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmodel',
            options={'ordering': ['-pk'], 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
    ]
