# Generated by Django 2.2 on 2020-07-19 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoarticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodelscheme',
            options={'ordering': ['-serial', '-pk'], 'verbose_name': 'Djangoarticle article', 'verbose_name_plural': 'Djangoarticle articles'},
        ),
        migrations.AlterModelOptions(
            name='categorymodelscheme',
            options={'ordering': ['-serial', '-pk'], 'verbose_name': 'Djangoarticle category', 'verbose_name_plural': 'Djangoarticle categories'},
        ),
        migrations.AlterField(
            model_name='articlemodelscheme',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoarticle.CategoryModelScheme'),
        ),
        migrations.AlterField(
            model_name='categorymodelscheme',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
