
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-24T11:04:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9800dd4016753c52db18b75f39f6364d186e1c8d",
 "version": "9.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
