
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-23T11:17:15+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "3be5f9c6cb1ab593fa9a0b47cae6421ea3c985e8",
 "version": "1.25.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
