
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-23T18:03:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6cff3275881d14662f95f3d83890e1e58edd1817",
 "version": "0.17.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
