
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-20T14:57:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "86a6a8227916eb68cd582eb37efc1213f67f0a78",
 "version": "1.7.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
