
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-23T12:05:54+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0bc5f9729e67b030c152cbf9e950caf4258080c",
 "version": "1.25.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
