
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-18T17:02:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6b17b1be13d73c22fcc2180f5a9fd5c1d6d06ea",
 "version": "1.3.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
