# Generated by Django 3.0.7 on 2020-06-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('like_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('likestarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='like_system.LikesTarget')),
                ('headline', models.CharField(max_length=500)),
            ],
            bases=('like_system.likestarget',),
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('likestarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='like_system.LikesTarget')),
                ('headline', models.CharField(max_length=500)),
            ],
            bases=('like_system.likestarget',),
        ),
    ]
