# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AdiEmsWebApiV2DtoSchemaAsyncQueryData(Model):
    """Represents the tabular results of a data source query obtained from an
    async query.

    All required parameters must be populated in order to send to Azure.

    :param rows: Required. An array of arrays representing the resulting data
     rows of a query. Each inner array represents a single results row
    :type rows: list[list[object]]
    :param has_more_rows: Required. Whether the query has one or more rows in
     its result set at an index greater than the last row returned
    :type has_more_rows: bool
    """

    _validation = {
        'rows': {'required': True},
        'has_more_rows': {'required': True},
    }

    _attribute_map = {
        'rows': {'key': 'rows', 'type': '[[object]]'},
        'has_more_rows': {'key': 'hasMoreRows', 'type': 'bool'},
    }

    def __init__(self, *, rows, has_more_rows: bool, **kwargs) -> None:
        super(AdiEmsWebApiV2DtoSchemaAsyncQueryData, self).__init__(**kwargs)
        self.rows = rows
        self.has_more_rows = has_more_rows
