
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-16T03:22:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "96517c52ce3fd6153a9ed079df7a38ea5affd2d7",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
