
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-07-16T18:18:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddc783fb33408f3956ac65f3dd3a4352070a8e71",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
