
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-24T04:26:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "08ee87753d929f77b7ff7200d223eb686300f16f",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
