
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-14T21:40:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd834daee6f9b402432d28dfc60c0db475758e8e",
 "version": "v1.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
