
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-16T06:57:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "aecb0f3ea062a929c6cba6854cdeca8aa59a71d3",
 "version": "v0.7.11a10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
