
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-20T10:07:20-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0538d6e9b615dbe37636941fc37a11d29a373e85",
 "version": "0.2.2a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
