__version__ = "2.1.0"
__git_commiter_name__ = "Itai Shirav"
__git_commiter_email__ = "itais@infinidat.com"
__git_branch__ = '(HEAD detached at v2.1.0)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ebdadb3aee147036bcc6d143709999fc0ce888a9'
__git_head_subject__ = 'Finished Release v2.1.0'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2020-07-16 07:22:18'
