
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-22T00:27:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e44fa5c2d92dc6ea8fbe20738e7e7433c52abc1d",
 "version": "0.8.155"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
