
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-22T11:24:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7dbbd652cc1be42538a72f7bcd80b87895bef91",
 "version": "1.2.4-alpha.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
