# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkMGHImageIOPython
else:
    import _itkMGHImageIOPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _itkMGHImageIOPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _itkMGHImageIOPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.itkMatrixPython
import itk.vnl_vectorPython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.vnl_matrixPython
import itk.itkPointPython
import itk.itkFixedArrayPython
import itk.vnl_vector_refPython
import itk.itkVectorPython
import itk.itkCovariantVectorPython
import itk.vnl_matrix_fixedPython
import itk.ITKCommonBasePython
import itk.ITKIOImageBaseBasePython

def itkMGHImageIO_New():
    return itkMGHImageIO.New()

class itkMGHImageIO(itk.ITKIOImageBaseBasePython.itkImageIOBase):
    r"""Proxy of C++ itkMGHImageIO class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkMGHImageIOPython.itkMGHImageIO___New_orig__)
    Clone = _swig_new_instance_method(_itkMGHImageIOPython.itkMGHImageIO_Clone)
    __swig_destroy__ = _itkMGHImageIOPython.delete_itkMGHImageIO
    cast = _swig_new_static_method(_itkMGHImageIOPython.itkMGHImageIO_cast)

    def New(*args, **kargs):
        """New() -> itkMGHImageIO

        Create a new object of the class itkMGHImageIO and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMGHImageIO.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkMGHImageIO.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkMGHImageIO.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkMGHImageIO in _itkMGHImageIOPython:
_itkMGHImageIOPython.itkMGHImageIO_swigregister(itkMGHImageIO)
itkMGHImageIO___New_orig__ = _itkMGHImageIOPython.itkMGHImageIO___New_orig__
itkMGHImageIO_cast = _itkMGHImageIOPython.itkMGHImageIO_cast


def itkMGHImageIOFactory_New():
    return itkMGHImageIOFactory.New()

class itkMGHImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    r"""Proxy of C++ itkMGHImageIOFactory class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkMGHImageIOPython.itkMGHImageIOFactory___New_orig__)
    RegisterOneFactory = _swig_new_static_method(_itkMGHImageIOPython.itkMGHImageIOFactory_RegisterOneFactory)
    __swig_destroy__ = _itkMGHImageIOPython.delete_itkMGHImageIOFactory
    cast = _swig_new_static_method(_itkMGHImageIOPython.itkMGHImageIOFactory_cast)

    def New(*args, **kargs):
        """New() -> itkMGHImageIOFactory

        Create a new object of the class itkMGHImageIOFactory and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkMGHImageIOFactory.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkMGHImageIOFactory.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkMGHImageIOFactory.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkMGHImageIOFactory in _itkMGHImageIOPython:
_itkMGHImageIOPython.itkMGHImageIOFactory_swigregister(itkMGHImageIOFactory)
itkMGHImageIOFactory___New_orig__ = _itkMGHImageIOPython.itkMGHImageIOFactory___New_orig__
itkMGHImageIOFactory_RegisterOneFactory = _itkMGHImageIOPython.itkMGHImageIOFactory_RegisterOneFactory
itkMGHImageIOFactory_cast = _itkMGHImageIOPython.itkMGHImageIOFactory_cast



