# coding: utf-8

"""
    Dash Hudson - Insta

    A Smarter Way to Grow on Instagram  To use the following APIs you will need an access token. An access token can be obtained by contacting Dash Hudson support.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tomek@dashhudson.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import brandpanel_api
from brandpanel_api.models.user_create import UserCreate  # noqa: E501
from brandpanel_api.rest import ApiException


class TestUserCreate(unittest.TestCase):
    """UserCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserCreate(self):
        """Test UserCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = brandpanel_api.models.user_create.UserCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
