# coding: utf-8

"""
    Dash Hudson - Insta

    A Smarter Way to Grow on Instagram  To use the following APIs you will need an access token. An access token can be obtained by contacting Dash Hudson support.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: tomek@dashhudson.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import brandpanel
from brandpanel.api.default_api import DefaultApi  # noqa: E501
from brandpanel.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = brandpanel.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_user(self):
        """Test case for update_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
