
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-07-14T21:00:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca8b0f7b174a360a6c2ab8ff30f9394c9836f035",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
