# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"query_statcast": "00_data_acquisition.ipynb",
         "query_db": "00_data_acquisition.ipynb",
         "AL_teams": "01_data_processing.ipynb",
         "add_pitcher_team": "01_data_processing.ipynb",
         "add_postouts": "01_data_processing.ipynb",
         "outs_per_inning": "01_data_processing.ipynb",
         "batters_faced": "01_data_processing.ipynb",
         "get_games_pitchers_years": "01_data_processing.ipynb",
         "preliminary_clean": "01_data_processing.ipynb",
         "last": "01_data_processing.ipynb",
         "aggregate_at_bats": "01_data_processing.ipynb",
         "create_indicator": "01_data_processing.ipynb",
         "accumulate": "01_data_processing.ipynb",
         "feature_engineering": "01_data_processing.ipynb",
         "embedding_cols": "02_data_pipeline.ipynb",
         "feature_cols": "02_data_pipeline.ipynb",
         "cols": "02_data_pipeline.ipynb",
         "add_targets": "02_data_pipeline.ipynb",
         "stack_into_df": "02_data_pipeline.ipynb",
         "scale": "02_data_pipeline.ipynb",
         "encode_col": "02_data_pipeline.ipynb",
         "encode_embedding_cols": "02_data_pipeline.ipynb",
         "at_bat_aggs": "02_data_pipeline.ipynb",
         "add_val_flags": "02_data_pipeline.ipynb",
         "prep_data_for_modeling": "02_data_pipeline.ipynb",
         "cm": "03_metrics.ipynb",
         "get_starts_from_labels": "03_metrics.ipynb",
         "mean_pa_diff": "03_metrics.ipynb",
         "mean_target_diff": "03_metrics.ipynb",
         "preds_histogram": "03_metrics.ipynb",
         "print_all_metrics": "03_metrics.ipynb",
         "get_game_df": "04_inference.ipynb",
         "is_valid_starter": "04_inference.ipynb",
         "test_front_pad": "04_inference.ipynb",
         "game_df2tensor": "04_inference.ipynb",
         "load_drsa": "04_inference.ipynb",
         "make_altair_hist": "04_inference.ipynb",
         "get_starts": "05_utils.ipynb",
         "front_pad": "05_utils.ipynb",
         "PTPDataset": "05_utils.ipynb",
         "save_model": "05_utils.ipynb",
         "load_model": "05_utils.ipynb"}

modules = ["data/acquisition.py",
           "data/processing.py",
           "data/pipeline.py",
           "metrics.py",
           "inference.py",
           "utils.py"]

doc_url = "https://collinprather.github.io/pull-the-pitcher/"

git_url = "https://github.com/collinprather/pull_the_pitcher/tree/master/"

def custom_doc_links(name): return None
