
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-24T20:43:51+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "7154cd0f388fea2c38934fd7407fb2d574e2111e",
 "version": "0.5.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
