# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2020-07-14 15:11:14.942740
__version__ = '3.0.2'