
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-23T17:49:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "35ee949d52f5c6df7397f4c48550508ed441e11d",
 "version": "2020.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
